# Generated by Django 5.1.2 on 2024-10-15 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoiceitem",
            old_name="rate",
            new_name="price_per_unit",
        ),
    ]
